* FACTORS
** ALGORITHM TO FIND ALL FACTORS
A simple algorithm can be used to find all factors of a number. This guarantees
all factors are found. We will use the number 24 as an example. 

1. start with 1

[[images/factors/factor1.svg]]

2. try each each other integer in order

[[images/factors/factor2.svg]]

3. remove any any numbers that do not divide exactly (like 5 in this example). 

[[images/factors/factors3.svg]]

4. Stop when you reach repeating numbers. (like "4×6" and "6×4" in this example)

5. All factors are now listed.

[[images/factors/factor4.svg]]

TODO insert latex
** PROGRAMMMING LANGUAGES
*** C
#+begin_src c  
void find_factors(int n){
  for(int i = 1; i <= n/2; i++){
    if(n % i == 0){
      printf("%d,", i);
    }
  }
  printf("%d \n", n);
}
#+end_src
*** C++
#+begin_src c++
std::vector<int> find_factors(int n){
  std::vector<int> result;

  for(int i = 1; i <= n/2; i++){
    if(n % i == 0){
      result.push_back(i);
    }
  }
  
  result.push_back(n);
  return result;
}
#+end_src

* PRIME FACTORS
prime numbers are number that do not divide by anything other than itself and 1.
(it's only factors are itself an 1).
1 is not a prime number.

Any number can be broken down into a string of prime factors. 
this is called **prime factor decomposition** or **prime factorisation**
** ALGORITHM TO FIND ALL PRIME FACTORS
we will use the number 420 as an example.

1. split the number into 2 factors


2. if any number is not prime, split the results again

3. repeat step 2 on remaining non-prime numbers until only prime numbers remain


4. order the primes, writing as powers for any repeating primes

** PROGRAMMING LANGUAGES
*** C
print the prime factors
#+begin_src c  
void find_prime_factors(int n){

  while(n % 2 == 0){
    printf("2, ");
    n = n/2;
  }
  
  for(int i = 3; i < sqrt(n); i = i+2){
    while(n%i == 0){
      printf("%d, ", i);
      n = n/i;
    }
  }
  
  if(n > 2){
    printf("%d, ", n);
  }

    printf("\n");
}
#+end_src
Or, if you want the prime factors in an array
#+begin_src c 
#include <stdlib.h>
#include <stdio.h>
#include <math.h>

int get_prime_factors(int* arr, int n){
  int counter = 0;
  
  while(n % 2 == 0){
    arr[counter++] = 2;
    n = n/2;
  }

  for(int i = 3; i < sqrt(n); i += 2){
    while(n%i == 0){
      arr[counter++] = i;
      n = n/i;
    }
  }

  if(n > 2){
    arr[counter++] = n;
  }

  return counter;
}

int main(int argc, char** argv){
  #define BUFFER_SIZE 64
  int* arr = (int*)malloc(sizeof(int) * BUFFER_SIZE);

  int arr_size = get_prime_factors(arr, 56);

  for(int i = 0; i < arr_size; i++){
    printf("%d, ", arr[i]);
  }

  printf("\n");
  
  return EXIT_SUCCESS;
}
#+end_src
*** C++
#+begin_src c   
#include <iostream>
#include <vector>
#include <cmath>

std::vector<int> get_prime_factors(int n){
  std::vector<int> prime_factors;
  while(n % 2 == 0){
    prime_factors.push_back(2);
    n = n / 2;
  }

  for(int i = 3; i < std::sqrt(n); i += 2){
    while(n % i == 0){
      prime_factors.push_back(i);
      n = n/i;
    }
  }

  if(n > 2){
    prime_factors.push_back(n);
  }

  return prime_factors;
}

int main(int argc, char** argv){

  std::vector<int> prime_factors = get_prime_factors(56);

  for(int i = 0; i < prime_factors.size(); i++){
    std::cout << prime_factors[i] << ", ";
  }

  std::cout << "\n"; 
  return 0;
}
#+end_src

*** PYTHON
#+begin_src python
 def get_prime_factors(n):
    prime_factors = []

    while n % 2 == 0:
        prime_factors.append(2)
        n = int(n / 2)

    if n > 2:
        prime_factors.append(n)

    return prime_factors

prime_factors = get_prime_factors(56)

for i in prime_factors:
    print(i)
#+end_src
